require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'LifeTime' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  
  # https://github.com/react-native-community/react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  # https://github.com/zo0r/react-native-push-notification/issues/1168
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  
  target 'LifeTimeTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

