# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)

package = load_json(json_path: "./package.json")
version = package["version"]
app = load_json(json_path: "./app.json")
appName = app["name"]
xcodeproj = "./ios/" + appName +".xcodeproj"
workspace = "./ios/" + appName +".xcworkspace"

platform :android do
  desc "Submit a new Beta Build to Google Play Store Beta"
  lane :beta do
    increment_version_code(
      gradle_file_path: "android/app/build.gradle",
    )
    gradle(
      project_dir: "android",
      task: "bundle",
      flavor: "prod",
      build_type: "Release",
    )
    notification(subtitle: appName+" for Android", message: "Build complete")
    upload_to_play_store(
      track: "internal",
    )
    notification(subtitle: appName+" for Android", message: "Upload complete")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      project_dir: "android",
      task: "clean assembleRelease",
    )
    upload_to_play_store
  end
end

platform :ios do
  desc "iOS: Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number_in_xcodeproj(
      xcodeproj: xcodeproj,
      target: appName,
    )
    build_app(
      workspace: workspace,
      scheme: appName,
      export_xcargs: "-allowProvisioningUpdates",
    )
    notification(subtitle: appName+" for iOS", message: "Build complete")
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
    )
    notification(subtitle: appName+" for iOS", message: "Upload complete")
  end
end

desc "iOS: Bump version"
private_lane :iosVersionBump do
  increment_version_number_in_xcodeproj(
    version_number: version,
    xcodeproj: xcodeproj,
    target: appName,
  )
end

desc "Bump version"
lane :versionBump do
  iosVersionBump
end
