open Js.Date

type locale

type localeOptions = {
  locale: option<locale>,
  weekStartsOn: option<int>,
}

@bs.module("date-fns")
external formatRelative: (t, t, option<localeOptions>) => string = "formatRelative"
@bs.module("date-fns") external formatISO: (t, option<localeOptions>) => string = "formatISO"
@bs.module("date-fns")
external formatRFC3339: (t, option<localeOptions>) => string = "formatRFC3339"

@bs.module("date-fns") external addMilliseconds: (t, float) => t = "addMilliseconds"
@bs.module("date-fns") external subMilliseconds: (t, float) => t = "subMilliseconds"
@bs.module("date-fns") external addSeconds: (t, float) => t = "addSeconds"
@bs.module("date-fns") external subSeconds: (t, float) => t = "subSeconds"
@bs.module("date-fns") external addMinutes: (t, float) => t = "addMinutes"
@bs.module("date-fns") external subMinutes: (t, float) => t = "subMinutes"
@bs.module("date-fns") external addHours: (t, float) => t = "addHours"
@bs.module("date-fns") external subHours: (t, float) => t = "subHours"
@bs.module("date-fns") external addDays: (t, float) => t = "addDays"
@bs.module("date-fns") external subDays: (t, float) => t = "subDays"
@bs.module("date-fns") external addBusinessDays: (t, float) => t = "addBusinessDays"
@bs.module("date-fns") external subBusinessDays: (t, float) => t = "subBusinessDays"
@bs.module("date-fns") external addWeeks: (t, float) => t = "addWeeks"
@bs.module("date-fns") external subWeeks: (t, float) => t = "subWeeks"
@bs.module("date-fns") external addMonths: (t, float) => t = "addMonths"
@bs.module("date-fns") external subMonths: (t, float) => t = "subMonths"
@bs.module("date-fns") external addQuarters: (t, float) => t = "addQuarters"
@bs.module("date-fns") external subQuarters: (t, float) => t = "subQuarters"
@bs.module("date-fns") external addYears: (t, float) => t = "addYears"
@bs.module("date-fns") external subYears: (t, float) => t = "subYears"
@bs.module("date-fns") external addISOWeekYears: (t, float) => t = "addISOWeekYears"
@bs.module("date-fns") external subISOWeekYears: (t, float) => t = "subISOWeekYears"
@bs.module("date-fns") external startOfDay: (t, option<localeOptions>) => t = "startOfDay"
@bs.module("date-fns") external endOfDay: (t, option<localeOptions>) => t = "endOfDay"
@bs.module("date-fns") external startOfWeek: (t, option<localeOptions>) => t = "startOfWeek"
@bs.module("date-fns") external endOfWeek: (t, option<localeOptions>) => t = "endOfWeek"
@bs.module("date-fns") external lastDayOfWeek: (t, option<localeOptions>) => t = "lastDayOfWeek"
@bs.module("date-fns") external startOfMonth: (t, option<localeOptions>) => t = "startOfMonth"
@bs.module("date-fns") external endOfMonth: (t, option<localeOptions>) => t = "endOfMonth"
@bs.module("date-fns") external lastDayOfMonth: (t, option<localeOptions>) => t = "lastDayOfMonth"

// module Locales = {
//   @bs.module("date-fns/locale") external af: locale = "af"
//   @bs.module("date-fns/locale") external arDZ: locale = "ar-DZ"
//   @bs.module("date-fns/locale") external arSA: locale = "ar-SA"
//   @bs.module("date-fns/locale") external be: locale = "be"
//   @bs.module("date-fns/locale") external bg: locale = "bg"
//   @bs.module("date-fns/locale") external bn: locale = "bn"
//   @bs.module("date-fns/locale") external ca: locale = "ca"
//   @bs.module("date-fns/locale") external cs: locale = "cs"
//   @bs.module("date-fns/locale") external cy: locale = "cy"
//   @bs.module("date-fns/locale") external de: locale = "de"
//   @bs.module("date-fns/locale") external el: locale = "el"
//   @bs.module("date-fns/locale") external eo: locale = "eo"
//   @bs.module("date-fns/locale") external en: locale = "en"
//   @bs.module("date-fns/locale") external enUS: locale = "en-US"
//   @bs.module("date-fns/locale") external enGB: locale = "en-GB"
//   @bs.module("date-fns/locale") external enCA: locale = "en-CA"
//   @bs.module("date-fns/locale") external es: locale = "es"
//   @bs.module("date-fns/locale") external et: locale = "et"
//   @bs.module("date-fns/locale") external faIR: locale = "fa-IR"
//   @bs.module("date-fns/locale") external fi: locale = "fi"
//   @bs.module("date-fns/locale") external fil: locale = "fil"
//   @bs.module("date-fns/locale") external fr: locale = "fr"
//   @bs.module("date-fns/locale") external gl: locale = "gl"
//   @bs.module("date-fns/locale") external he: locale = "he"
//   @bs.module("date-fns/locale") external hr: locale = "hr"
//   @bs.module("date-fns/locale") external hu: locale = "hu"
//   @bs.module("date-fns/locale") external id: locale = "id"
//   @bs.module("date-fns/locale") external is: locale = "is"
//   @bs.module("date-fns/locale") external it: locale = "it"
//   @bs.module("date-fns/locale") external ja: locale = "ja"
//   @bs.module("date-fns/locale") external ka: locale = "ka"
//   @bs.module("date-fns/locale") external ko: locale = "ko"
//   @bs.module("date-fns/locale") external lt: locale = "lt"
//   @bs.module("date-fns/locale") external lv: locale = "lv"
//   @bs.module("date-fns/locale") external mk: locale = "mk"
//   @bs.module("date-fns/locale") external ms: locale = "ms"
//   @bs.module("date-fns/locale") external nl: locale = "nl"
//   @bs.module("date-fns/locale") external pl: locale = "pl"
//   @bs.module("date-fns/locale") external ptBr: locale = "pt-Br"
//   @bs.module("date-fns/locale") external pt: locale = "pt"
//   @bs.module("date-fns/locale") external ro: locale = "ro"
//   @bs.module("date-fns/locale") external ru: locale = "ru"
//   @bs.module("date-fns/locale") external sk: locale = "sk"
//   @bs.module("date-fns/locale") external sl: locale = "sl"
//   @bs.module("date-fns/locale") external sr: locale = "sr"
//   @bs.module("date-fns/locale") external sv: locale = "sv"
//   @bs.module("date-fns/locale") external th: locale = "th"
//   @bs.module("date-fns/locale") external tr: locale = "tr"
//   @bs.module("date-fns/locale") external ug: locale = "ug"
//   @bs.module("date-fns/locale") external uk: locale = "uk"
//   @bs.module("date-fns/locale") external vi: locale = "vi"
//   @bs.module("date-fns/locale") external zhCN: locale = "zh-CN"
//   @bs.module("date-fns/locale") external zhTW: locale = "zh-TW"
// }
