name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #   image: ubuntu:latest
    #   options: --privileged

    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
      - run: echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p

      - uses: actions/checkout@v1
      # - uses: ./.github/actions/action
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn install \
            --non-interactive \
            --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          CI: true
