name: iOS

on: [push, pull_request]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: npm run ruby:bundle

      - uses: mikehardy/buildcache-action@v1

      - run: npm run deps:ios:install

      - run: ./node_modules/.bin/react-native run-ios --configuration Release
