name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: yarn install --non-interactive --frozen-lockfile
      - run: yarn test
        env:
          CI: true
