name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:lts
      options: --privileged

    steps:
      - run: echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
      - uses: actions/checkout@v2
      # - uses: ./.github/actions/action
      - run: |
          yarn install \
            --non-interactive \
            --frozen-lockfile
      - run: yarn test
        env:
          CI: true
